name: Post canteen report

on:
  schedule:
    # 11:07 Monday--Friday in CEST
    - cron: "7 9 * * 1-5"
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute script
        run: python main.py
        env:
          __VUT_USERNAME: ${{ secrets.VUT_USERNAME }}
          __VUT_PASSWORD: ${{ secrets.VUT_PASSWORD }}
          __IG_USERNAME: ${{ secrets.IG_USERNAME }}
          __IG_PASSWORD: ${{ secrets.IG_PASSWORD }}